In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr=np.array([[1,2,3,4,5,6]])
print(arr[:2])  #output entire array like indexing 
print(arr[2:])  #slicing


[[1 2 3 4 5 6]]
[]


In [ ]:
np.zeros(3)# creates an array of zeros with 3 elements

array([0., 0., 0.])

In [ ]:
np.ones(3)#1.,1.,1.

array([1., 1., 1.])

In [ ]:
np.arange(0,10)#0,1,2,3,4,5,6,7,8,9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2)#0.,2.,4.,6.,8.

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(0,1,5)#0.,0.25,0.5,0.75,1.0

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Array properties

In [ ]:
np.array([1,2,3,4,5]).ndim  #dimension
np.array([[1,2,3],[4,5,6]]).shape  #shape
np.array([[1,2,3],[4,5,6]]).size   #size
# --- IGNORE ---
# Recent edits
# np.linspace(0,1,5)#0.,0.25,0.5,0.75,1.0
# np.arange(1,10,2)#0.,2.,4.,6.,8
# np.arange(0,10)#0,1,2,3,4,5,6,7,8,9
# np.ones(3,.2)#1.,1.,1.


6

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
arr_int=arr.astype(int)
print(arr_int)
print(arr_int.dtype)

[[1 2 3]
 [4 5 6]]
int64


In [ ]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[0,1])  
print(mat[:,2])  
print(mat[:,1])

2
[3 6 9]
[2 5 8]


In [ ]:
a=np.array([1,2,3])
b=a
b[0]=100
print(a)  #[100,2,3]
print(b)  #[100,2,3]
#This is the not god way to copy array
# ------------------------------------------
c=a.copy()
c[0]=200
print(a)  #[100,2,3]
print(c)  #[200,2,3]

[100   2   3]
[100   2   3]
[100   2   3]
[200   2   3]


In [ ]:
d=np.array([1,2,3,4,5])
print(d+10)
print(d*2)

[11 12 13 14 15]
[ 2  4  6  8 10]


In [ ]:
arr=np.array([1,2,3,4,5])
print(np.std(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))  #index of min value
print(np.argmax(arr))  #index of max value
print(np.sqrt(arr))
print(np.log1p(arr))
print(np.exp(arr))

1.4142135623730951
15
3.0
3.0
2.0
1
5
0
4
[1.         1.41421356 1.73205081 2.         2.23606798]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr[arr>2])  #boolean indexing
print(arr>2)  #boolean array

[3 4 5]
[False False  True  True  True]


In [ ]:
# Element-wise multiplication
# in normal maths we use dot product but in numpy its element-wise multiplication
# like a=[[1,2],[3,4]] and b=[[5,6],[7,8]]
#   c=a*b=[[1*5 2*6]
#          [3*7 4*8]]=[[5,12],[21,32]]
# Broadcasting
# when we do operation on two arrays of different shapes numpy automatically expands the smaller array to match the shape of the larger array
# how nampy checks for Broadcasting(right to left Rule):
# 1. if the arrays have different number of dimensions, prepend the shape of the smaller array with ones until both shapes have the same length.
# 2. the arrays are compatible in a dimension if they have the same size in that dimension, or if one of the arrays has size 1 in that dimension.
# 3. the arrays can be broadcast together if they are compatible in all dimensions.
# 4. after broadcasting, each array behaves as if it had shape equal to the element-wise maximum of shapes of the two input arrays.
# 5. in any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension.
# ------>they are equal,OR-|
#                          |-->this dimension is compatible in broadcasting
# ------->one of them is 1-|
# -----adding examples-----
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,20,30])
c=a+b
print(c)
# c=[[1,2,3]+[10,20,30]
#   [4,5,6]]+[10,20,30]
# c=[[1+10 2+20 3+30]
#    [4+10 5+20 6+30]]=[[11,22,33],[14,25,36]]
# ----outer example-----
d=np.array([[1],[2],[3]])
e=np.array([10,20,30])
f=d+e
print(f)
# f=[[1] +[10,20,30]
#    [2] +[10,20,30]
#    [3]]+[10,20,30]
# f=[[1+10 1+20 1+30]
#    [2+10 2+20 2+30]
#    [3+10 3+20 3+30]]=[[11,21,31],[12,22,32],[13,23,33]]
# -----Scalar example-----
g=np.array([[1,2,3],[4,5,6]])
h=10
i=g*h
print(i)
# i=[[1,2,3] * [[10,10,10]
#    [4,5,6]]   [10,10,10]]
# i=[[1*10 2*10 3*10]
#    [4*10 5*10 6*10]]=[[10,20,30],[40,50,60]]
# ---Failure Scenarios---
# 1. Shapes are not compatible:
a1=np.array([[1,2,3],[4,5,6]])
b1=np.array([1,2])  # incompatible shape
try:
    c1=a1+b1
except ValueError as e:
    print("Error:", e)
    # Output: Error: shapes (2,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)
# 2. Different number of dimensions without proper alignment:
a2=np.array([[1,2,3],[4,5,6]])
b2=np.array([[1,2],[3,4]])  # incompatible shape
try:
    c2=a2+b2
except ValueError as e:
    print("Error:", e)
    # Output: Error: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 1)
# 3. Incompatible sizes in specific dimensions:
a3=np.array([[1,2,3],[4,5,6]])
b3=np.array([[1],[2],[3],[4]])  # incompatible shape
try:
    c3=a3+b3
except ValueError as e:
    print("Error:", e)
    # Output: Error: shapes (2,3) and (4,1) not aligned: 2 (dim 0) != 4 (dim 0)
# 4. Image vs mask mismatch:
image=np.array([[1,2,3],[4,5,6],[7,8,9]])
mask=np.array([[1,0],[0,1]])  # incompatible shape
try:
    result=image*mask
except ValueError as e:
    print("Error:", e)
    # Output: Error: shapes (3,3) and (2,2) not aligned: 3 (dim 0) != 2 (dim 0)
# 5. Higher-dimensional arrays with incompatible shapes:
# 6. neutral network bias(shape Transfer)


[[11 22 33]
 [14 25 36]]
[[11 21 31]
 [12 22 32]
 [13 23 33]]
[[10 20 30]
 [40 50 60]]
Error: operands could not be broadcast together with shapes (2,3) (2,) 
Error: operands could not be broadcast together with shapes (2,3) (2,2) 
Error: operands could not be broadcast together with shapes (2,3) (4,1) 
Error: operands could not be broadcast together with shapes (3,3) (2,2) 


In [ ]:
# alignment issues in broadcasting# --- IGNORE ---
# broadcasting is a powerful mechanism that allows numpy to perform operations on arrays of different shapes and sizes. However, it can lead to alignment issues if the shapes of the arrays are not compatible. When performing operations on arrays, numpy checks for compatibility based on the rules of broadcasting. If the shapes of the arrays do not align properly, it can result in errors or unexpected results. It is important to understand the rules of broadcasting and ensure that the shapes of the arrays are compatible when performing operations to avoid alignment issues.
# Recent edits
# Element-wise multiplication
#   |--> in normal maths we use dot product but in numpy its element-wise multiplication
# ------------------------------------
# application---->FEATURE SCALING

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr+10) # the numpy uses the broadcasting to add or any thing to the entire array without any loop

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:
a=np.array([[1,2],[4,5]])
b=np.array([[10,30],[20,40]])
print(np.dot(a,b)) # dot product

[[ 50 110]
 [140 320]]


In [ ]:
print(a.T) # transpose of arr1

[[1 4]
 [2 5]]


In [ ]:
# np.random.rand(5) # generates 5 random numbers between 0 and 1
np.random.rand(2,3) # generates 2x3 random numbers between 0 and 1
# np.random.randint(0,10,5) # generates 5 random integers between 0 and 10


array([[0.03507303, 0.13682472, 0.71984362],
       [0.14010706, 0.89663812, 0.10639059]])

Reshaping Array

In [ ]:
arr=np.arange(12) # generates an array of integers from 0 to 9
print(arr)
print(arr.reshape(3,4)) # reshapes the array to 3x4

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(a))
print(np.sum(a,axis=0)) # sum along the columns
print(np.sum(a,axis=1)) # sum along the rows

45
[12 15 18]
[ 6 15 24]


Where in numpy

In [ ]:
arr=np.array([[1,2,3],[-9,5,6],[7,8,9]])
res=np.where(arr<0,0,arr) # replaces all negative values with 0
print(res)

[[1 2 3]
 [0 5 6]
 [7 8 9]]


In [ ]:
a = np.arange(12)          # shape (12,)
print(a.reshape(-1, 1))