In [1]:
import numpy as np

In [14]:
arr=np.array([[78,85,90],[45,60,55],[88,92,95],[30,40,35],[65,70,75]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)
# --------------------
a=arr[2][1]
# print(a)
# print((np.swapaxes(arr,0,1))[1])
# # ----------------------
# print(np.mean(arr,axis=1))
# print(np.mean(arr,axis=0))
# -------------------------
# b=(np.mean(arr,axis=1))>=80
# print(b)
# # --------------------------
# print(np.where(arr>=50,1,0))
# print(np.where(arr<40,0,arr))
# # --------------------------
# c=np.where(arr<50,0,arr)
# c=np.where((c>=50) & (c<70),6,c)
# c=np.where((c>=70) & (c<85),8,c)
# c=np.where(c>=85,10,c)
# print(c)
# # --------------------------
# arr2=arr.copy()
# arr[0][0]=0
# print(arr2)
# # --------------------------
arr1=np.random.randint(120,650,size=(4,7))
print(arr1)
print(arr1.shape,arr1.size,arr1.dtype)
# 120 to 650---->shap(4,7)
# -------------------------
avg=np.mean(arr,axis=0)
print(avg)
print(np.where(arr[:,2]>=avg[2],True,False))

# print(np.take_along_axis(arr,arr[2].argsort(),axis=0))
# --------------------------
a=np.random.randint(120,300,size=(4,7))
print(a)
#----------------------



[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
(5, 3)
15
int64
[[431 413 555 362 473 180 456]
 [482 563 311 521 312 178 644]
 [155 600 233 377 457 453 486]
 [129 349 496 347 363 366 173]]
(4, 7) 28 int32
[61.2 69.4 70. ]
[ True False  True False  True]
[[138 213 131 297 242 232 216]
 [186 280 213 195 198 134 122]
 [297 238 215 162 132 176 285]
 [241 133 248 144 220 126 240]]


In [8]:
a9=np.array([3,2])+5
a5=np.arange(3)+5
a8=np.array([10,20,30,40])
print(a5)
print(a8[[0,3]])

[5 6 7]
[10 40]
